In [1]:
import keras


Using TensorFlow backend.


In [2]:

from keras.models import Sequential
from keras.layers import Dense,Dropout,Flatten,Activation
from keras import backend as K
import numpy as np

In [3]:
import pickle
f=open("trainX.pickle","rb")
images=pickle.load(f)
f=open("trainY.pickle","rb")
label=pickle.load(f)

In [4]:
img_r,img_c=28,28
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(images,label,test_size=0.2,random_state=1)

In [110]:
import pandas as pd
pd.DataFrame(y_train).describe()


0
count  48000.000000
mean       4.497521
std        2.871846
min        0.000000
25%        2.000000
50%        4.000000
75%        7.000000
max        9.000000

In [5]:
print(x_train.shape)

(48000, 28, 28)


In [6]:
print(y_train.shape)

(48000,)


In [7]:
K.image_data_format()

'channels_last'

In [8]:
batch_size=128
num_classes=10
epochs=10

In [9]:
x_train = x_train.astype('float32')
x_test = x_test.astype('float32')
x_train /= 255
x_test /= 255
print('x_train shape:', x_train.shape)
print(x_train.shape[0], 'train samples')
print(x_test.shape[0], 'test samples')

# convert class vectors to binary class matrices
y_train = keras.utils.to_categorical(y_train, num_classes)
y_test = keras.utils.to_categorical(y_test, num_classes)

x_train shape: (48000, 28, 28)
48000 train samples
12000 test samples


In [10]:
x_train = np.reshape(x_train, (48000, 784))
x_test = np.reshape(x_test, (12000, 784))

In [11]:
y_test.shape

(12000, 10)

# made ANN model

In [12]:
model = Sequential()
model.add(Dense(800, input_dim=784) )
model.add(Activation('relu'))


model.add(Dense(500) )
model.add(Activation('relu'))

model.add(Dense(300))
model.add(Activation('relu'))

model.add(Dense(10))
model.add(Activation('softmax'))
model.summary()
model.compile(loss=keras.losses.categorical_crossentropy,
              optimizer=keras.optimizers.Adadelta(),
              metrics=['accuracy'])

W0624 10:13:36.812381 21196 deprecation_wrapper.py:119] From C:\Users\gaurav\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:74: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

W0624 10:13:36.979216 21196 deprecation_wrapper.py:119] From C:\Users\gaurav\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0624 10:13:36.983217 21196 deprecation_wrapper.py:119] From C:\Users\gaurav\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:4138: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.

W0624 10:13:37.083217 21196 deprecation_wrapper.py:119] From C:\Users\gaurav\Anaconda3\lib\site-packages\keras\optimizers.py:790: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

W0624 10:13:37.095218 21196 deprecation_wrapper.py:119] From C:\Users\gaurav

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 800)               628000    
_________________________________________________________________
activation_1 (Activation)    (None, 800)               0         
_________________________________________________________________
dense_2 (Dense)              (None, 500)               400500    
_________________________________________________________________
activation_2 (Activation)    (None, 500)               0         
_________________________________________________________________
dense_3 (Dense)              (None, 300)               150300    
_________________________________________________________________
activation_3 (Activation)    (None, 300)               0         
_________________________________________________________________
dense_4 (Dense)              (None, 10)                3010      
__________

In [13]:
model.fit(x_train, y_train,
          batch_size=batch_size,
          epochs=epochs,
          verbose=1,
          validation_data=(x_test, y_test))

score = model.evaluate(x_test, y_test, verbose=0)
print('Test loss:', score[0])
print('Test accuracy:', score[1])

W0624 10:13:42.066707 21196 deprecation.py:323] From C:\Users\gaurav\Anaconda3\lib\site-packages\tensorflow\python\ops\math_grad.py:1250: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
W0624 10:13:42.198677 21196 deprecation_wrapper.py:119] From C:\Users\gaurav\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:986: The name tf.assign_add is deprecated. Please use tf.compat.v1.assign_add instead.



Train on 48000 samples, validate on 12000 samples
Epoch 1/10
48000/48000 [==============================] - 18s 380us/step - loss: 0.6181 - acc: 0.7721 - val_loss: 0.4898 - val_acc: 0.8184
Epoch 2/10
48000/48000 [==============================] - 16s 343us/step - loss: 0.4099 - acc: 0.8466 - val_loss: 0.4153 - val_acc: 0.8458
Epoch 3/10
48000/48000 [==============================] - 18s 369us/step - loss: 0.3590 - acc: 0.8659 - val_loss: 0.3444 - val_acc: 0.8710
Epoch 4/10
48000/48000 [==============================] - 18s 370us/step - loss: 0.3283 - acc: 0.8775 - val_loss: 0.3364 - val_acc: 0.8768
Epoch 5/10
48000/48000 [==============================] - 17s 347us/step - loss: 0.3035 - acc: 0.8852 - val_loss: 0.3470 - val_acc: 0.8649
Epoch 6/10
48000/48000 [==============================] - 17s 359us/step - loss: 0.2846 - acc: 0.8918 - val_loss: 0.3259 - val_acc: 0.8773
Epoch 7/10
48000/48000 [==============================] - 17s 346us/step - loss: 0.2680 - acc: 0.8982 - val_loss: 0.

In [106]:
y_test.shape

(12000, 10)

In [14]:
y_pred=model.predict(x_test)
y_pred=y_pred.round()


In [15]:
import pandas as pd
pd.to_pickle(y_pred,path="testY.pickle")

# tried to make CNN

In [54]:
# from keras.layers import Convolution2D
# from keras.layers import MaxPooling2D
# from keras.preprocessing.image import ImageDataGenerator
# model = Sequential()
# model.add(Convolution2D(32,3, 3 ,activation='relu',input_shape=(32,32,3)))

# model.add(MaxPooling2D(pool_size=(2, 2)))

# model.add(Flatten())
# model.add(Dense(128, activation='relu'))

# model.add(Dense(10, activation='softmax'))
# model.compile(loss=keras.losses.categorical_crossentropy,
#               optimizer=keras.optimizers.Adadelta(),
#               metrics=['accuracy'])
# # (x_train, y_train), (x_test, y_test) = cifar10.load_data()
# # y_train = np_utils.to_categorical(y_train, num_classes)
# # y_test = np_utils.to_categorical(y_test, num_classes)

# # datagen = ImageDataGenerator(
# #     featurewise_center=True,
# #     featurewise_std_normalization=True,
# #     rotation_range=20,
# #     width_shift_range=0.2,
# #     height_shift_range=0.2,
# #     horizontal_flip=True)

# # compute quantities required for featurewise normalization
# # (std, mean, and principal components if ZCA whitening is applied)
# # datagen.fit(x_train)

# # fits the model on batches with real-time data augmentation:
# # model.fit_generator(datagen.flow(x_train, y_train, batch_size=32),
# #                     steps_per_epoch=len(x_train) / 32, epochs=epochs)

# # # here's a more "manual" example
# # for e in range(epochs):
# #     print('Epoch', e)
# #     batches = 0
# #     for x_batch, y_batch in datagen.flow(x_train, y_train, batch_size=32):
# #         model.fit(x_batch, y_batch)
# #         batches += 1
# #         if batches >= len(x_train) / 32:
# #             # we need to break the loop by hand because
# #             # the generator loops indefinitely
# #             break
# # # # model.compile(optimizer="adam",loss='binary_crossentropy')
# model.summary()

# tried some preprocessing on image

In [55]:
# datagen = ImageDataGenerator(
#     featurewise_center=True,
#     featurewise_std_normalization=True,
#     rotation_range=20,
#     width_shift_range=0.2,
#     height_shift_range=0.2,
#     horizontal_flip=True)


# # compute quantities required for featurewise normalization
# # (std, mean, and principal components if ZCA whitening is applied)
# # datagen.fit(x_train)

# #fits the model on batches with real-time data augmentation:
# model.fit_generator(datagen.flow(x_train, y_train, batch_size=32),
#                     steps_per_epoch=len(x_train) / 32, epochs=epochs)

# # here's a more "manual" example
# for e in range(epochs):
#     print('Epoch', e)
#     batches = 0
#     for x_batch, y_batch in datagen.flow(x_train, y_train, batch_size=32):
#         model.fit(x_batch, y_batch)
#         batches += 1
#         if batches >= len(x_train) / 32:
#             # we need to break the loop by hand because
#             # the generator loops indefinitely
#             break
# # # model.compile(optimizer="adam",loss='binary_crossentropy')
# model.summary()

In [56]:
# model.fit(x_train, y_train,
#           batch_size=batch_size,
#           epochs=epochs,
#           verbose=1,
#           validation_data=(x_test, y_test))

# score = model.evaluate(x_test, y_test, verbose=0)
# print('Test loss:', score[0])
# print('Test accuracy:', score[1])

In [57]:
# # import matplotlib.pyplot as plt
# x_train.reshape()
# # %matplotlib inline # Only use this if using iPython
# # image_index = 7777 # You may select anything up to 60,000
#  print(x_train.shape) # The label is 8
# # plt.imshow(x_train[image_index], cmap='Greys')

In [36]:
arr4d = np.expand_dims(x_train,0)

In [39]:
arr4d

array([[[[0.        , 0.        , 0.        , ..., 0.        ,
          0.        , 0.        ],
         [0.        , 0.        , 0.        , ..., 0.        ,
          0.        , 0.        ],
         [0.        , 0.        , 0.        , ..., 0.        ,
          0.        , 0.        ],
         ...,
         [0.        , 0.        , 0.        , ..., 0.        ,
          0.        , 0.        ],
         [0.        , 0.        , 0.        , ..., 0.        ,
          0.        , 0.        ],
         [0.        , 0.        , 0.        , ..., 0.        ,
          0.        , 0.        ]],

        [[0.        , 0.        , 0.        , ..., 0.        ,
          0.        , 0.        ],
         [0.        , 0.        , 0.        , ..., 0.        ,
          0.        , 0.        ],
         [0.        , 0.        , 0.        , ..., 0.        ,
          0.        , 0.        ],
         ...,
         [0.        , 0.        , 0.04705882, ..., 0.        ,
          0.        , 0. 

In [196]:
y_pred=model.predict(x_test)

In [167]:
y_pred[100].round(decimals=10)


array([1.712000e-07, 0.000000e+00, 0.000000e+00, 0.000000e+00,
       1.370000e-08, 0.000000e+00, 1.408000e-07, 0.000000e+00,
       9.999997e-01, 0.000000e+00], dtype=float32)

In [165]:
y_pred[10]

array([3.5885103e-14, 4.9544862e-20, 1.0958191e-17, 1.8411712e-21,
       7.0825465e-16, 1.7605640e-18, 1.5282253e-14, 2.3762686e-16,
       1.0000000e+00, 4.6964853e-14], dtype=float32)

In [177]:
y_test.shape


(12000, 10)

In [176]:
y_train.shape

(48000, 10)

In [197]:
import pandas as pd

FileNotFoundError: [Errno 2] No such file or directory: ''